server:
  port: 8081
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/hb_student_tracker
    username: student 
    password: azubike88
  jpa:    show-sql: true
    hibernate:      ddl-auto: update

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
 